<?php 

function hubspot_connect_webform_submission_insert($node, $submission) {
     
  if (!empty($node->field_subtitle['und'][0]['value'])) {
     ksort($node->webform['components']);
    foreach ($node->webform['components'] as $form) {          
      if ($form['type']!="fieldset") {
        $post_data[$form['form_key']] = "";
      }
      
    }    
    $values=array();
    ksort($submission->data);

foreach ($submission->data as $info) {
    $data=$info[0];    
    array_push($values,$data);
}
$i=0;
foreach ($post_data as $key => $value) {
  $post_data[$key]=$values[$i];
  $i++;
}
    /*$post_data['utm_medium']=$_SESSION['utm_medium_palace'];
    $post_data['source']=$_SESSION['utm_source_palace'];
    $post_data['utm_term']=$_SESSION['utm_term_palace'];
    $post_data['utm_content']=$_SESSION['utm_content_palace'];
    $post_data['utm_campaign']=$_SESSION['utm_campaign_palace'];*/
//traverse array and prepare data for posting (key1=value1)
foreach ( $post_data as $key => $value) {
    $post_items[] = $key . '=' . $value;
}

//create the final string to be posted using implode()
$post_string = implode ('&', $post_items);

  
//create cURL connection
$curl_connection = curl_init($node->field_subtitle['und'][0]['value']);

//set options
curl_setopt($curl_connection, CURLOPT_CONNECTTIMEOUT, 30);
curl_setopt($curl_connection, CURLOPT_USERAGENT, 
  "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)");
curl_setopt($curl_connection, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl_connection, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($curl_connection, CURLOPT_FOLLOWLOCATION, 1);

//set data to be posted
curl_setopt($curl_connection, CURLOPT_POSTFIELDS, $post_string);

//perform our request
$result = curl_exec($curl_connection);

//show information regarding the request
/*print_r(curl_getinfo($curl_connection));
echo curl_errno($curl_connection) . '-' .curl_error($curl_connection);*/

//close the connection
curl_close($curl_connection);
}

}


